# 3x3 Householder QR Demo

This demo constructs a $3\times 3$ QR factorization using Householder reflectors.

In [65]:
import numpy as np
import numpy.linalg as la

In [75]:
A = np.random.randn(5, 4)
A

array([[-0.30431346,  0.17126633,  0.67160276, -0.70178148],
       [ 0.82405851,  1.25941552,  0.54632226, -0.16751628],
       [ 0.74840768, -2.04402523,  0.2556131 ,  1.39932852],
       [-0.24484575, -0.51119763,  0.35777757, -0.78316031],
       [-0.79564562,  0.02910628,  0.27340105,  0.85254303]])

Householder reflector:
$$I-2\frac{vv^T}{v^Tv}$$

Choose $v=a-\|a\|e_1$.

In [78]:
a = A[:, 0]

v = a - la.norm(a, 2)*np.array([1,0,0,0,0])
H1 = np.eye(5) - 2*np.outer(v,v)/(v@v)

In [79]:
A1 = H1 @ A
A1.round(3)

array([[ 1.423, -0.311,  0.093,  0.447],
       [-0.   ,  1.489,  0.822, -0.716],
       [ 0.   , -1.835,  0.506,  0.902],
       [-0.   , -0.58 ,  0.276, -0.62 ],
       [-0.   , -0.193,  0.007,  1.382]])

NB: Never build full Householder matrices in actual code! (Why? How?)

In [80]:
a = A1[:, 1].copy()
a[:1] = 0
v = a - la.norm(a, 2)*np.array([0,1,0,0,0])
H2 = np.eye(5) - 2*np.outer(v,v)/(v@v)

In [81]:
A2 = H2 @ A1
A2.round(3)

array([[ 1.423, -0.311,  0.093,  0.447],
       [-0.   ,  2.441,  0.055, -1.076],
       [ 0.   ,  0.   , -0.973,  0.206],
       [-0.   ,  0.   , -0.192, -0.84 ],
       [-0.   ,  0.   , -0.149,  1.309]])

In [82]:
a = A2[:, 2].copy()
a[:2] = 0
v = a - la.norm(a, 2)*np.array([0,0,1,0,0])
H3 = np.eye(5) - 2*np.outer(v,v)/(v@v)

In [83]:
A3 = H3 @ A2
A3.round(3)

array([[ 1.423, -0.311,  0.093,  0.447],
       [-0.   ,  2.441,  0.055, -1.076],
       [ 0.   , -0.   ,  1.003, -0.234],
       [-0.   ,  0.   , -0.   , -0.883],
       [-0.   ,  0.   , -0.   ,  1.276]])

In [87]:
R = A3

In [88]:
Q = (H3 @ H2 @ H1).T
la.norm(np.dot(Q, R) - A)

1.3634220254142561e-15

In [ ]:
# (one more round of Householder would kill the last row entry--but in the interest of keeping the notebook the same as in class, I've left the code way it is)