# Lecture 22


### Olver and Shakiban 4.3 --- using a different method

## Using Householder reflections to put A in upper-triangular form

In [78]:
A = randn(5,3); R = A


R =

   -2.0518    0.2820   -0.2991
   -0.3538    0.0335    0.0229
   -0.8236   -1.3337   -0.2620
   -1.5771    1.1275   -1.7502
    0.5080    0.3502   -0.2857



In [79]:
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % using (1:end,1:end) is unnecessary
% but it helps to see the pattern


R =

    2.7854   -0.3921    1.2337
    0.0000   -0.0158    0.1350
         0   -1.4485   -0.0010
   -0.0000    0.9077   -1.2505
         0    0.4210   -0.4466



In [80]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end))


R =

    2.7854   -0.3921    1.2337
    0.0000    1.7605   -0.7519
         0    0.0000   -0.7242
   -0.0000   -0.0000   -0.7973
         0   -0.0000   -0.2364



In [81]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))


R =

    2.7854   -0.3921    1.2337
    0.0000    1.7605   -0.7519
         0    0.0000    1.1028
   -0.0000   -0.0000    0.0000
         0   -0.0000    0.0000



At the end of this, $A$ is in upper-triangular form.  This is the $R$ in the $A = QR$ factorization.  That is, we've found a way to apply $Q^T = Q^{-1}$ to $A$ to get $Q^TA = R$.  To understand how to construct $Q$ we have think about what we are doing at each stage.

Start with $Q_0 = I$ and $R_0 = A$.  Then

$$A = Q_0 R_0 = Q_0 H_1^T H_1 R_0$$

where $H_1$ is the Householder reflection constructed based on the first column of $R_0$.  And, we have used that $H_1$ is an orthogonal matrix, $H_1^T H_1 = I$.  But let's look at $H_1$ closer:

In [82]:
R = A;
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
H1 = eye(length(x)) - 2*w*w'


H1 =

   -0.7366   -0.1270   -0.2957   -0.5662    0.1824
   -0.1270    0.9907   -0.0216   -0.0414    0.0133
   -0.2957   -0.0216    0.9497   -0.0964    0.0311
   -0.5662   -0.0414   -0.0964    0.8154    0.0595
    0.1824    0.0133    0.0311    0.0595    0.9808



In [83]:
H1' - H1


ans =

     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0



We see that $H_1 = H_1^T$ is symmetric, so that $H_1 = H_1^{-1}$.  This is why these are called reflections.  If you reflect, and reflect again, you should be back where you started.

So, 

$$A = Q_0 R_0 = Q_0 H_1^T H_1 R_0 = (Q_0 H_1) (H_1 R_0)$$.

As before, the following computes $H_1 R_0$ to get $R_1$:

In [84]:
R = A;
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % Applies H1 to R


R =

    2.7854   -0.3921    1.2337
    0.0000   -0.0158    0.1350
         0   -1.4485   -0.0010
   -0.0000    0.9077   -1.2505
         0    0.4210   -0.4466



To compute $Q_0 H_1$, we note that $Q_0$ is the identity matrix:

In [85]:
Q = eye(size(A,1));
Q = Q(:,1:end) - 2*(Q(:,1:end)*w)*w' % Q appears on the left of w, w'
% because Q0 appears to the left of H1


Q =

   -0.7366   -0.1270   -0.2957   -0.5662    0.1824
   -0.1270    0.9907   -0.0216   -0.0414    0.0133
   -0.2957   -0.0216    0.9497   -0.0964    0.0311
   -0.5662   -0.0414   -0.0964    0.8154    0.0595
    0.1824    0.0133    0.0311    0.0595    0.9808



And repeat:

In [86]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end))
% You can do R(2:end,:) = R(2:end,:) - 2*w*(w'*R(2:end,:))
% but we know that most of the first column of R(2:end,:) is zero
% so it makes sense to exclude it from the computation
% But we cannot do that with the rows of Q:
Q(:,2:end) = Q(:,2:end) - 2*(Q(:,2:end)*w)*w'


R =

    2.7854   -0.3921    1.2337
    0.0000    1.7605   -0.7519
         0    0.0000   -0.7242
   -0.0000   -0.0000   -0.7973
         0   -0.0000   -0.2364


Q =

   -0.7366   -0.0039   -0.1953   -0.6291    0.1532
   -0.1270   -0.0093   -0.8370    0.4696    0.2503
   -0.2957   -0.8234    0.2959    0.3133    0.2211
   -0.5662    0.5143    0.3568    0.5314   -0.0722
    0.1824    0.2395    0.2155   -0.0561    0.9272



In [87]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))
Q(:,3:end) = Q(:,3:end) - 2*(Q(:,3:end)*w)*w'


R =

    2.7854   -0.3921    1.2337
    0.0000    1.7605   -0.7519
         0    0.0000    1.1028
   -0.0000   -0.0000    0.0000
         0   -0.0000    0.0000


Q =

   -0.7366   -0.0039    0.5502   -0.3038    0.2497
   -0.1270   -0.0093    0.1566    0.9032    0.3789
   -0.2957   -0.8234   -0.4682   -0.0201    0.1222
   -0.5662    0.5143   -0.6030    0.1126   -0.1964
    0.1824    0.2395   -0.2997   -0.2810    0.8606



Verify the properties:

In [89]:
A - Q*R % good factorization


ans =

   1.0e-15 *

         0   -0.1110   -0.1665
    0.1665    0.3192   -0.6245
   -0.1110    0.4441    0.2220
   -0.4441    0.4441    0.2220
   -0.1110   -0.0555    0.2220



In [90]:
Q'*Q % Q is indeed orthogonal


ans =

    1.0000    0.0000    0.0000   -0.0000   -0.0000
    0.0000    1.0000    0.0000   -0.0000   -0.0000
    0.0000    0.0000    1.0000    0.0000   -0.0000
   -0.0000   -0.0000    0.0000    1.0000    0.0000
   -0.0000   -0.0000   -0.0000    0.0000    1.0000



In [91]:
Q*Q'


ans =

    1.0000    0.0000   -0.0000   -0.0000   -0.0000
    0.0000    1.0000    0.0000   -0.0000   -0.0000
   -0.0000    0.0000    1.0000    0.0000    0.0000
   -0.0000   -0.0000    0.0000    1.0000    0.0000
   -0.0000   -0.0000    0.0000    0.0000    1.0000



## Solving a least-squares problem

In [100]:
A = randn(5,3); R = A;  b = ones(5,1);

### By normal equations:

In [101]:
An = A'*A;
bn = A'*b


bn =

   -4.4961
    1.2299
   -1.3695



In [102]:
x0 = An\bn  % Solves (A'*A)x = A'* b, the normal equations
norm(A*x0-b)  % residual


x0 =

   -0.4943
    2.6440
    0.4565


ans =

    0.3886



In [103]:
R = [A,b];
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % R1


R =

    3.1559   -0.0993    0.8713   -1.4246
    0.0000    0.4941    0.5420    1.5758
   -0.0000    0.2787   -0.8231    0.0309
   -0.0000   -0.4329    1.3971   -0.6952
   -0.0000   -0.0045   -0.2628   -0.0543



In [104]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end)) % R1


R =

    3.1559   -0.0993    0.8713   -1.4246
    0.0000   -0.7136    0.7919   -1.5253
   -0.0000         0   -0.7654   -0.6847
   -0.0000         0    1.3075    0.4163
   -0.0000         0   -0.2637   -0.0427



In [105]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))


R =

    3.1559   -0.0993    0.8713   -1.4246
    0.0000   -0.7136    0.7919   -1.5253
   -0.0000         0    1.5379    0.7021
   -0.0000         0         0   -0.3709
   -0.0000         0         0    0.1160



In [106]:
x = R(4:end,4);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(4:end,4:end) = R(4:end,4:end) - 2*w*(w'*R(4:end,4:end))


R =

    3.1559   -0.0993    0.8713   -1.4246
    0.0000   -0.7136    0.7919   -1.5253
   -0.0000         0    1.5379    0.7021
   -0.0000         0         0    0.3886
   -0.0000         0         0    0.0000



In [108]:
x = Backsub(R(1:3,:))
x0


x =

   -0.4943
    2.6440
    0.4565


x0 =

   -0.4943
    2.6440
    0.4565



In [110]:
abs(R(4,4))
norm(A*x0-b)


ans =

    0.3886


ans =

    0.3886

